### ISSUE TITLE
Is there a way to query without populating? 

### ISSUE THREAD

**Issue by aa2kb** [dynamoose/dynamoose#1030]
### Summary:
1. I am querying Task Model which have a reference key of project, When I get the response back all tasks keys are populated. How can I change the query to not populate and return simple dyanmoDB docs.
2. Also one more thing does dynamoose cache the populated document? or query every time for the same key

#### Schema
```
const query = {
      "userID": { "eq": userId }
    };

const tasks = await Task.query(query).exec();
```

#### Task Schema
```
const TaskSchema = new dynamoose.Schema(
  {
    "userID": {
      "type": String,
      "hashKey": true
    },
    "createdAt": {
      "type": Date,
      "rangeKey": true,
      "default": () => Date.now()
    },
    "title": String,
    "project": Project,
    "isDeleted": {
      "type": Boolean,
      "default": false
    },
    "isCompleted": {
      "type": Boolean,
      "default": false
    },
    "clickupTaskID": String,
  }, {
  "timestamps": {
    "createdAt": null,
    "updatedAt": "updatedAt"
  }
});
```

### Environment:

Operating System: mac
Operating System Version: BigSur
Node.js version (`node -v`): 12.19.0
NPM version: (`npm -v`): 6.14.8
Dynamoose version: ^2.3.0

### Other:
- [x] I have read through the Dynamoose documentation before posting this issue
- [x] I have searched through the GitHub issues (including closed issues) and pull requests to ensure this question has not already been raised before
- [x] I have searched the internet and Stack Overflow to ensure this question hasn't been raised or answered before
- [x] I have filled out all fields above
- [x] I am running the latest version of Dynamoose

**Comment by fishcharlie** [comment]
@aa2kb 

> How can I change the query to not populate and return simple dyanmoDB docs

What do you mean by `simple DynamoDB docs`? What is the current result and expected result? Those are fields in the issue template that you didn't fill out.

> Also one more thing does dynamoose cache the populated document? or query every time for the same key

No. There is currently no caching layer within Dynamoose. We might do some minor caching for things like attribute type information and schema information. But nothing in regards to documents.

**Comment by aa2kb** [comment]
This is what I get when I query through Dyanmoose
```
[
  {
      "userID": "3",
      "updatedAt": "2020-11-14T14:19:27.739Z",
      "project": {
          "createdAt": "2020-11-14T11:01:48.987Z",
          "ID": "e293cceb-6aba-4402-bbf7-49b17b678117",
          "name": "Project 1",
          "updatedAt": "2020-11-14T11:01:48.987Z"
      },
      "createdAt": "2020-11-14T14:19:27.740Z",
      "isDeleted": false,
      "title": "Fetch Sync Data",
      "isCompleted": false
  },
  {
      "userID": "3",
      "updatedAt": "2020-11-14T14:19:30.581Z",
      "project": {
          "createdAt": "2020-11-14T11:01:48.987Z",
          "ID": "e293cceb-6aba-4402-bbf7-49b17b678117",
          "name": "Project 1",
          "updatedAt": "2020-11-14T11:01:48.987Z"
      },
      "createdAt": "2020-11-14T14:19:30.582Z",
      "isDeleted": false,
      "title": "Email API",
      "isCompleted": false
  },
  {
      "userID": "3",
      "updatedAt": "2020-11-14T14:19:32.543Z",
      "project": {
          "createdAt": "2020-11-14T11:01:48.987Z",
          "ID": "e293cceb-6aba-4402-bbf7-49b17b678117",
          "name": "Project 1",
          "updatedAt": "2020-11-14T11:01:48.987Z"
      },
      "createdAt": "2020-11-14T14:19:32.544Z",
      "isDeleted": false,
      "title": "cron analytics",
      "isCompleted": false
  },
  {
      "userID": "3",
      "updatedAt": "2020-11-14T14:19:34.168Z",
      "project": {
          "createdAt": "2020-11-14T11:01:48.987Z",
          "ID": "e293cceb-6aba-4402-bbf7-49b17b678117",
          "name": "Project 1",
          "updatedAt": "2020-11-14T11:01:48.987Z"
      },
      "createdAt": "2020-11-14T14:19:34.170Z",
      "isDeleted": false,
      "title": "create nested operations",
      "isCompleted": false
  },
  {
      "userID": "3",
      "updatedAt": "2020-11-14T15:28:20.555Z",
      "project": {
          "createdAt": "2020-11-14T11:01:48.987Z",
          "ID": "e293cceb-6aba-4402-bbf7-49b17b678117",
          "name": "Project 1",
          "updatedAt": "2020-11-14T11:01:48.987Z"
      },
      "createdAt": "2020-11-14T15:28:21.564Z",
      "isDeleted": false,
      "title": "add user db",
      "isCompleted": false
  }
]
```

Using 
```
const tasks = await Task.query(query).exec();
```

The thing is Dynamoose is populating project again and again in each item `task`
What if I need my data to be unpopulated? The way it's stored in DynamoDB

Example
![image](https://user-images.githubusercontent.com/5059604/99181438-64fb7480-2750-11eb-861b-411ff368d30b.png)

Because Dynamoose must be querying for each `task` item to populate the key `project` 
which means exhausting my RCU, 

PS:
but if its cached this means dynamoose should only look for that same id only once for the population while going through a query


I hope you got my point. Thank you

**Comment by fishcharlie** [comment]
@aa2kb That is super weird. It should only populate when you call [`document.populate`](https://dynamoosejs.com/guide/Document#documentpopulatesettings-callback). Kinda sounds like a bug. Could you create a MCVE zip it up and upload it here?

**Comment by aa2kb** [comment]
@fishcharlie okay sure will upload that over here
